import { Link, useLocation } from "@tanstack/react-router";
import { AnimatePresence, motion } from "motion/react";
import { ArrowDown, ArrowRight, Instagram, Linkedin, Menu, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import logoAsset from "../assets/logo.png.asset.json";
import heroAsset from "../assets/event-hero.webp.asset.json";
import aboutAsset from "../assets/about.jpg.asset.json";
import corporateAsset from "../assets/corporate.png.asset.json";
import aiAsset from "../assets/ai.jpg.asset.json";
import sketchAsset from "../assets/sketch.jpg.asset.json";
import tradingAsset from "../assets/trading.png.asset.json";
import enclosedAsset from "../assets/enclosed.jpg.asset.json";
import booth360Asset from "../assets/booth360.jpg.asset.json";
import contactAsset from "../assets/contact.jpg.asset.json";

const nav = [
  ["About", "/about"],
  ["Event Services", "/#services"],
  ["Case Study", "/casestudy"],
  ["Photo Booth Installation", "/photo-booth-installation"],
  ["Corporate Events", "/corporateevents"],
] as const;

const services = [
  { title: "360 Booth", href: "/360-booth-hire", image: booth360Asset.url },
  { title: "Trading Cards", href: "/trading-card-booth", image: tradingAsset.url },
  { title: "AI Sketch Bots", href: "/ai-sketch-bots-hire", image: sketchAsset.url },
  { title: "AI Booth", href: "/ai-booth", image: aiAsset.url },
  { title: "Enclosed Photo Booth", href: "/enclosed-photo-booth", image: enclosedAsset.url },
  { title: "Corporate Experiences", href: "/corporateevents", image: corporateAsset.url },
];

const pageData: Record<string, { title: string; subtitle: string; image: string; sections: { title: string; body: string }[] }> = {
  "ai-booth": { title: "AI Booth Hire", subtitle: "A refined AI-powered photo booth experience delivering bespoke creative transformations at scale.", image: aiAsset.url, sections: [{ title: "Overview.", body: "The AI Booth blends premium photography with intelligent image generation to create high-quality, on-brand transformations in seconds." }, { title: "What Is the AI Booth?", body: "Guests step into a polished booth experience, take a portrait and select from a range of bespoke creative styles developed for your event or campaign." }, { title: "How the Experience Works.", body: "Every journey is simple and intuitive: capture, transform, review and share. Branded digital delivery makes every image instantly social-ready." }, { title: "AI Transformations & Creative Styles", body: "From editorial portraits to imaginative brand worlds, each visual direction can be tailored to campaign objectives and guest profiles." }] },
  "ai-sketch-bots-hire": { title: "AI Sketch Bots Hire", subtitle: "A flagship experiential activation combining AI, robotics, and bespoke brand storytelling.", image: sketchAsset.url, sections: [{ title: "Overview.", body: "AI Sketch Bots transform guest portraits into one-of-a-kind illustrated keepsakes, drawn live by robotic arms." }, { title: "What Is the AI Sketch Bots?", body: "A theatrical blend of portrait capture, artificial intelligence and precise robotic drawing that attracts crowds and starts conversations." }, { title: "How the Experience Works.", body: "A guest portrait becomes a custom illustration before the robot draws it live. Guests leave with a physical, branded artwork." }, { title: "Illustration Styles & Creative Options", body: "Choose a visual language designed around your brand, event theme or campaign creative." }] },
  "trading-card-booth": { title: "Trading Card Booth", subtitle: "Turn guests into collectible cards.", image: tradingAsset.url, sections: [{ title: "Overview.", body: "A playful, premium booth that turns every guest into a branded collectible." }, { title: "What Is the Trading Card Booth?", body: "Guests pose, personalise their stats and receive a professionally designed physical or digital trading card." }, { title: "How the Experience Works.", body: "Capture, customise and print in a fast-flowing guest journey designed for high engagement." }, { title: "Branding & Customisation", body: "Layouts, card backs, ratings, graphics and packaging can all be aligned to your campaign." }] },
  "enclosed-photo-booth": { title: "Enclosed Photo Booth", subtitle: "A private, classic photo booth experience that never goes out of style.", image: enclosedAsset.url, sections: [{ title: "Overview.", body: "The timeless photo booth, elevated with premium finishes, modern technology and complete brand customisation." }, { title: "What Is an Enclosed Booth?", body: "A private space where guests can relax, pose and create authentic photo-strip moments." }, { title: "How the Experience Works.", body: "Step inside, follow the on-screen countdown and collect a beautifully printed keepsake within moments." }, { title: "Branding & Customisation", body: "From the exterior wrap to the screen journey and final print, every detail can carry your identity." }] },
  "360-booth-hire": { title: "360 Booth Hire", subtitle: "Capture high-impact, slow-motion video content that guests love and brands value.", image: booth360Asset.url, sections: [{ title: "Overview.", body: "A dynamic video experience that captures guests from every angle and delivers instantly shareable content." }, { title: "What Is the 360 Booth?", body: "Guests stand on a platform while a camera moves smoothly around them to create cinematic slow-motion clips." }, { title: "How the Experience Works.", body: "Our team guides every guest, adds branded effects and delivers the finished video directly to their phone." }, { title: "Branding & Customisation", body: "Custom overlays, music, intros, outros and platform wraps create a completely cohesive activation." }] },
};

function Header() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); addEventListener("scroll", onScroll); return () => removeEventListener("scroll", onScroll); }, []);
  return <header className={`site-header ${scrolled ? "is-scrolled" : ""}`}>
    <div className="nav-shell">
      <Link to="/" aria-label="36ixty Booths home"><img src={logoAsset.url} alt="36ixty Booths" className="brand-logo" /></Link>
      <nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav>
      <a className="button button-primary desktop-contact" href="/contact">Contact Us</a>
      <button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open}>{open ? <X /> : <Menu />}</button>
    </div>
    <AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>{nav.map(([label, href]) => <a onClick={() => setOpen(false)} key={label} href={href}>{label}</a>)}<a href="/contact">Contact Us</a></motion.nav>}</AnimatePresence>
  </header>;
}

function Footer() {
  return <footer className="footer"><div className="footer-wordmark">3<span>6</span>IXTY</div><div className="footer-grid"><p>Experiential photo booths and interactive event experiences, delivered across the UK and internationally.</p><div><strong>Explore</strong><a href="/about">About</a><a href="/#services">Services</a><a href="/casestudy">Case Studies</a></div><div><strong>Contact</strong><a href="mailto:hello@36ixtybooths.com">hello@36ixtybooths.com</a><a href="/contact">Start a project</a><span className="socials"><Instagram /><Linkedin /></span></div></div><p className="copyright">© 2026 36ixty Booths. All rights reserved.</p></footer>;
}

const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <motion.div className={className} initial={{ opacity: 0, y: 44 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .75, ease: [.22, 1, .36, 1] }}>{children}</motion.div>;

export function SiteLayout({ children }: { children: React.ReactNode }) { return <><Header />{children}<Footer /></>; }

export function HomePage() {
  return <SiteLayout>
    <section className="hero dark-band"><motion.div className="hero-media" initial={{ clipPath: "inset(0 50% 0 50%)" }} animate={{ clipPath: "inset(0 0% 0 0%)" }} transition={{ duration: 1.2, ease: [.76, 0, .24, 1] }}><img src={heroAsset.url} alt="Guests enjoying a 36ixty photo booth experience" fetchPriority="high" /><div className="hero-copy"><span className="scribble">〰</span><h1>36IXTY</h1><p>Experiential Photo Booths & Interactive Event Experiences</p><a href="#intro" aria-label="Scroll to introduction"><ArrowDown /></a></div></motion.div></section>
    <section id="intro" className="section intro-section"><Reveal><h2 className="display-title"><span>Welcome to</span>36IXTY BOOTHS</h2></Reveal><div className="split"><Reveal className="media-frame"><img src={aboutAsset.url} alt="Guests at a 36ixty event" loading="lazy" /></Reveal><Reveal className="body-copy"><p className="eyebrow">About 36ixty</p><h3>We create moments people want to keep.</h3><p>At 36ixty, we create standout event experiences that guests genuinely engage with — and brands can measure. From premium photo booth hire to AI-powered activations and permanent installations, we blend technology, design, and a polished guest experience to deliver content that is instantly shareable and always on-brand.</p><p>We work with corporate clients, agencies, venues, and brands to deliver experiences that look exceptional, run seamlessly, and leave a lasting impression.</p></Reveal></div></section>
    <section className="stats dark-band"><div><strong>500+</strong><span>Events Delivered</span></div><div><strong>10+ Years</strong><span>Events Experience</span></div><div><strong>5★</strong><span>Google Rating</span></div><div><strong>Global</strong><span>Delivery</span></div></section>
    <section id="services" className="section"><Reveal><p className="eyebrow">What we do</p><h2 className="section-title">Interactive experiences,<br />built around your brand.</h2></Reveal><div className="service-grid">{services.map((service, i) => <motion.a href={service.href} className="service-card" key={service.title} whileHover={{ y: -8 }}><img src={service.image} alt="" loading="lazy" /><span>0{i + 1}</span><h3>{service.title}</h3><ArrowRight /></motion.a>)}</div></section>
    <section className="feature-band"><Reveal><p className="eyebrow">Why 36ixty</p><h2>Creative technology.<br />Flawless delivery.</h2></Reveal><div className="feature-list"><article><span>01</span><h3>Permanent Installations</h3><p>Always-on experiences built to drive repeat footfall, capture guest data and generate ongoing content.</p></article><article><span>02</span><h3>UK & International Delivery</h3><p>Full logistical and operational support for campaigns, conferences and experiences worldwide.</p></article><article><span>03</span><h3>Experiential Partnership</h3><p>Professional on-site teams, bespoke creative and reliable technology from brief to delivery.</p></article></div></section>
    <section className="cta-band"><p>Have an event in mind?</p><h2>Let’s make it unforgettable.</h2><a className="button button-light" href="/contact">Start a project <ArrowRight /></a></section>
  </SiteLayout>;
}

export function AboutPage() { return <SiteLayout><PageHero title="Your Moments, Our Magic ®" subtitle="We combine creativity, technology and thoughtful service to turn events into experiences people remember." image={aboutAsset.url} /><section className="section"><div className="split"><Reveal><p className="eyebrow">Why Choose Us?</p><h2 className="section-title">More than a booth supplier.</h2></Reveal><Reveal className="body-copy"><p>We are an experiential partner for brands, agencies and venues. Every activation is considered from the guest journey through to the final shareable moment.</p><p>Our trained teams deliver every experience with confidence, warmth and attention to detail.</p></Reveal></div></section><section className="section dark-band"><h2 className="section-title">Services</h2><div className="service-grid">{services.map(s => <a className="service-card" href={s.href} key={s.title}><img src={s.image} alt="" /><h3>{s.title}</h3><ArrowRight /></a>)}</div></section></SiteLayout>; }

function PageHero({ title, subtitle, image }: { title: string; subtitle: string; image: string }) { return <section className="page-hero"><motion.img src={image} alt="" initial={{ scale: 1.08 }} animate={{ scale: 1 }} transition={{ duration: 1.4 }} /><div className="page-hero-overlay" /><motion.div className="page-hero-copy" initial={{ opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .25, duration: .8 }}><h1>{title}</h1><p>{subtitle}</p></motion.div></section>; }

export function ServicePage({ slug }: { slug: string }) { const data = pageData[slug] ?? pageData["ai-booth"]; if (!data) return null; return <SiteLayout><PageHero title={data.title} subtitle={data.subtitle} image={data.image} /><section className="editorial-sections">{data.sections.map((s, i) => <Reveal className="editorial-row" key={s.title}><span>0{i + 1}</span><h2>{s.title}</h2><p>{s.body}</p></Reveal>)}</section><section className="cta-band"><p>Bring your brief to life.</p><h2>Book {data.title}</h2><a className="button button-light" href="/contact">Get in touch <ArrowRight /></a></section></SiteLayout>; }

export function CorporatePage() { return <SiteLayout><PageHero title="Corporate Events" subtitle="Interactive event experiences that engage guests, amplify brands and deliver measurable value." image={corporateAsset.url} /><section className="section"><Reveal><p className="eyebrow">Make Every Moment Move</p><h2 className="section-title">Designed for brands.<br />Remembered by guests.</h2></Reveal><div className="split"><Reveal className="body-copy"><h3>Corporate Ties</h3><p>We work with agencies, venues and in-house teams to create polished activations for conferences, launches, awards, exhibitions and international campaigns.</p><p>Every touchpoint can be branded, every interaction considered, and every result measured.</p></Reveal><Reveal className="media-frame"><img src={booth360Asset.url} alt="Corporate event activation" /></Reveal></div></section><section className="section dark-band"><h2 className="section-title">Event Highlights</h2><div className="service-grid">{services.slice(0,3).map(s=><a className="service-card" href={s.href} key={s.title}><img src={s.image} alt="" /><h3>{s.title}</h3></a>)}</div></section></SiteLayout>; }

export function InstallationPage() { return <SiteLayout><PageHero title="Permanent Photo Booth Installations ®" subtitle="Always-on experiences designed for venues, destinations and long-term commercial value." image={enclosedAsset.url} /><section className="editorial-sections">{[{title:"Overview",body:"36ixty designs, builds and supports permanent passport-style booth installations for high-footfall venues."},{title:"What Is a Permanent Passport-Style Booth?",body:"A beautifully integrated, self-service experience that captures portraits, data and memorable branded content every day."},{title:"Branding & Customisation",body:"Cabinet finishes, user journeys, print formats and digital delivery are tailored to the venue and its audience."},{title:"Book Your Consultation Today",body:"Talk to our team about your venue, commercial objectives and installation requirements."}].map((s,i)=><Reveal className="editorial-row" key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></Reveal>)}</section></SiteLayout>; }

export function CaseStudiesPage() { const studies=[{title:"Westcoast",image:corporateAsset.url},{title:"Snyk AI",image:aiAsset.url},{title:"Savoys Club",image:enclosedAsset.url},{title:"WIFS 25",image:tradingAsset.url},{title:"Reading FC",image:booth360Asset.url},{title:"Park Plaza",image:sketchAsset.url}]; return <SiteLayout><section className="listing-hero"><p className="eyebrow">Case Studies & Gallery</p><h1>Work that creates<br />a reaction.</h1></section><section className="case-grid">{studies.map((s,i)=><a href={`/${s.title.toLowerCase().replaceAll(" ","")}`} className="case-card" key={s.title}><div><img src={s.image} alt={`${s.title} event case study`} loading="lazy" /></div><span>0{i+1}</span><h2>{s.title}</h2><ArrowRight /></a>)}</section></SiteLayout>; }

export function ContactPage() { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <SiteLayout><PageHero title="Say Hello to 36IXTY BOOTHS" subtitle="Tell us what you’re planning. We’ll help shape the right experience." image={contactAsset.url} /><section className="contact-section"><Reveal><p className="eyebrow">Got Questions?</p><h2>Let’s start with<br />your event.</h2><p>Share a few details and our team will be in touch to discuss ideas, availability and the best format for your audience.</p><a href="mailto:hello@36ixtybooths.com">hello@36ixtybooths.com</a></Reveal>{sent?<motion.div className="success" initial={{opacity:0}} animate={{opacity:1}} role="status"><h3>Thank you.</h3><p>Your enquiry has been received. We’ll be in touch shortly.</p></motion.div>:<form onSubmit={submit}><label>Name<input name="name" required autoComplete="name" /></label><label>Email<input type="email" name="email" required autoComplete="email" /></label><label>Event date<input type="date" name="date" /></label><label>What are you planning?<textarea name="message" rows={5} required /></label><button className="button button-primary" type="submit">Send enquiry <ArrowRight /></button></form>}</section></SiteLayout>; }

export function GenericPage({ slug }: { slug: string }) { const label=slug.replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase()); return <SiteLayout><PageHero title={`Case Study ${label}.`} subtitle="A tailored 36ixty experience, designed around the client, audience and event objective." image={corporateAsset.url} /><section className="editorial-sections">{["Synopsis.","Client Objectives.","Services.","Challenges & Solutions."].map((title,i)=><Reveal className="editorial-row" key={title}><span>0{i+1}</span><h2>{title}</h2><p>We created a distinctive, fully branded guest experience with an intuitive journey, reliable live delivery and memorable content designed for sharing.</p></Reveal>)}</section></SiteLayout>; }

export function NotFoundPage() { return <SiteLayout><section className="not-found"><p>404</p><h1>This moment got away.</h1><a className="button button-primary" href="/">Back home</a></section></SiteLayout>; }